/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_ImageLoader_hpp
#define LDL_ImageLoader_hpp

/********************************************************************************************************************************
														Configuration
********************************************************************************************************************************/
#if defined(_MSC_VER)
    #if defined (LDL_IMAGE_SHARED)
        #define LDL_IMAGE_API __declspec(dllexport)
    #else
        #define LDL_IMAGE_API __declspec(dllimport)
    #endif
#endif

#if defined(__GNUC__)
    #if defined (LDL_IMAGE_SHARED)
        #define LDL_IMAGE_API __attribute__ ((visibility("default")))
    #else
        #define LDL_IMAGE_API
    #endif
#endif
/********************************************************************************************************************************
														LDL_ImageLoader
********************************************************************************************************************************/
class LDL_IMAGE_API LDL_ImageLoader
{
public:
	LDL_ImageLoader();
	~LDL_ImageLoader();
	bool Load(const char* path);
	bool Load(unsigned char* data, int size);
	int Bpp();
	int Width();
	int Heigth();
	unsigned char* Pixels();
private:
	void Clear();
	int            _Bpp;
	int            _Width;
	int            _Heigth;
	unsigned char* _Pixels;
};

#endif    