/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Formats.hpp"
#include <string.h>

ArtColor::ArtColor() :
	b(0),
	g(0),
	r(0),
	a(0)
{
}

void ArtHeader::Clear()
{
	memset(&h0, 0, sizeof(h0));
	memset(&stupid_color, 0, sizeof(stupid_color));
	memset(&frame_num_low, 0, sizeof(frame_num_low));
	memset(&frame_num, 0, sizeof(frame_num));
	memset(&palette_data1, 0, sizeof(palette_data1));
	memset(&palette_data2, 0, sizeof(palette_data2));
	memset(&palette_data3, 0, sizeof(palette_data3));
}

ArtFrameHeader::ArtFrameHeader() :
	width(0),
	height(0),
	size(0),
	c_x(0),
	c_y(0),
	d_x(0),
	d_y(0)
{
}

void ArtFile::Clear()
{
	_Palettes = 0;
	_Frames   = 0;
	_KeyFrame = 0;
	_Animated = false;

	_Header.Clear();
}

bool ArtFile::Load(const char* name)
{
	Clear();

	_File = fopen(name, "rb");

	if (_File != NULL)
	{
		fread(&_Header, sizeof(_Header), 1, _File);
	}

	_Animated = ((_Header.h0[0] & 0x1) == 0);


	for (size_t i = 0; i < 4; i++)
	{
		if (in_palette(_Header.stupid_color[i]))
		{
			_Palettes++;
		}
	}

	_Frames   = _Header.frame_num;
	_KeyFrame = _Header.frame_num_low;

	if (_Animated)
	{
		_Frames *= 8;
	}

	if (_Palettes > 0)
	{
		fread(&_PaletteData[0], sizeof(ArtTable), 1, _File);
	}

	if (_Palettes > 1)
	{
		fread(&_PaletteData[0], sizeof(ArtTable), 1, _File);
	}

	if (_Palettes > 2)
	{
		fread(&_PaletteData[0], sizeof(ArtTable), 1, _File);
	}

	for (size_t j = 0; j < _Frames; j++)
	{
		fread(&_FrameHeaders[j], sizeof(ArtFrameHeader), 1, _File);
	}

	return _File != NULL;
}

size_t ArtFile::Frames()
{
	return _Frames;
}

void ArtFile::Frame(ArtFrame* frame)
{
	Decode(frame);
}

bool ArtFile::Inc(ArtFrame* frame)
{
	px++;
	if (px >= (frame->_Header.width))
	{
		px = 0;
		py++;
	}
	if (py >= (frame->_Header.height)) return false;
	if (py < 0) return false;
	return true;
}

void ArtFile::Dec(ArtFrame* frame)
{
	px--;
	if (px < 0)
	{
		px = frame->_Header.width - 1;
		py--;
	}
}

void ArtFile::Decode(ArtFrame* frame)
{
	px = 0;
	py = 0;

	frame->_Header = _FrameHeaders[0];

	fread(&data, frame->_Header.size, 1, _File);

	if (frame->_Header.size < (frame->_Header.height * frame->_Header.width))
	{
		for (size_t p = 0; p < (frame->_Header.size); p++)
		{
			uint8_t ch = (data[p]);

			if (ch & 0x80)
			{
				int to_copy = ch & (0x7F);
				while (to_copy--)
				{
					p++;
					frame->_Pixels[Index(frame, px, py)] = data[p];
					Inc(frame);
				}
			}
			else
			{
				int to_clone = ch & (0x7F);
				p++;
				uint8_t src = (data[p]);

				while (to_clone--)
				{
					frame->_Pixels[Index(frame, px, py)] = src;
					Inc(frame);
				}
			}
		}
	}
	else
	{
		for (size_t p = 0; p < (frame->_Header.size); p++)
		{
			frame->_Pixels[Index(frame, px, py)] = data[p];
			Inc(frame);
		}
	}
}

size_t ArtFile::Index(ArtFrame* frame, int x, int y)
{
	return ((frame->_Header.width * y) + x);
}