/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef Frm_hpp
#define Frm_hpp

#include <LDL/LDL.hpp>

struct FrmFile
{
	enum
	{
		Max = 6
	};

	FrmFile();

	uint32_t version;
	uint16_t frames_per_second;
	uint16_t action_frame;
	uint16_t frames_per_direction;
	uint16_t shift_x[FrmFile::Max];
	uint16_t shift_y[FrmFile::Max];
	uint16_t offset[FrmFile::Max];
	uint32_t size;
	uint32_t dirs;
};

struct FrmFrame
{
	enum
	{
		Max = 1024 * 32
	};

	FrmFrame();
	~FrmFrame();

	uint16_t width;
	uint16_t height;
	uint8_t* indexes;
};

class FrmReader
{
public:
	FrmReader(LDL_ByteReader* reader);
	~FrmReader();
	bool Open(const char* path);
	void ReadFrmFile(FrmFile* dest);
	void ReadFrmFrame(FrmFrame* dest);
private:
	void ReadShiftX(FrmFile* dest);
	void ReadShiftY(FrmFile* dest);
	void ReadOffsets(FrmFile* dest);
	LDL_ByteReader* _Reader;
};

#endif