/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <LDL/LDL_Image.hpp>

#define STB_IMAGE_IMPLEMENTATION
#define STBI_NO_THREAD_LOCALS
#define STBI_NO_SIMD
#include "../dependencies/stb_image.h"  

LDL_ImageLoader::LDL_ImageLoader() :
	_Bpp(0),
	_Width(0),
	_Heigth(0),
	_Pixels(NULL)
{
}

LDL_ImageLoader::~LDL_ImageLoader()
{
	Clear();
}

bool LDL_ImageLoader::Load(const char* path)
{
	Clear();

	_Pixels = stbi_load(path, &_Width, &_Heigth, &_Bpp, STBI_default);

	if (_Width <= 0 || _Heigth <= 0 || _Bpp <= 0 || _Pixels == NULL)
	{
		return false;
	}

	return true;
}

bool LDL_ImageLoader::Load(unsigned char* data, int size)
{
	Clear();

	_Pixels = stbi_load_from_memory(data, size, &_Width, &_Heigth, &_Bpp, 0);

	if (_Width <= 0 || _Heigth <= 0 || _Bpp <= 0 || _Pixels == NULL)
	{
		return false;
	}

	return true;
}

int LDL_ImageLoader::Bpp()
{
	return _Bpp;
}

int LDL_ImageLoader::Width()
{
	return _Width;
}

int LDL_ImageLoader::Heigth()
{
	return _Heigth;
}

unsigned char* LDL_ImageLoader::Pixels()
{
	return _Pixels;
}

void LDL_ImageLoader::Clear()
{
	if (_Pixels != NULL)
	{
		stbi_image_free(_Pixels);
	}

	_Bpp    = 0;
	_Width  = 0;
	_Heigth = 0;
}
