/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <LDL/Windows/GL1Win.hpp>

LDL_WindowOpenGL1::LDL_WindowOpenGL1(LDL_Result* result, const LDL_Vec2i& pos, const LDL_Vec2i& size, const char* title, int mode) :
	_Result(result),
	_MainWindow(result, pos, size, title, mode),
	_HGLRC(NULL)
{
	PIXELFORMATDESCRIPTOR pfd;

	ZeroMemory(&pfd, sizeof(PIXELFORMATDESCRIPTOR));

	if (!_Result->Ok())
		return;

	_MainWindow._HDC = GetDC(_MainWindow._HWND);

	if (_MainWindow._HDC == NULL)
	{
		_Result->Message("GetDC failed");
		return;
	}

	pfd.nSize = sizeof(pfd);
	pfd.nVersion = 1;
	pfd.dwFlags = PFD_DRAW_TO_WINDOW | PFD_SUPPORT_OPENGL | PFD_DOUBLEBUFFER;
	pfd.iPixelType = PFD_TYPE_RGBA;
	pfd.cColorBits = 24;
	pfd.cDepthBits = 16;
	pfd.iLayerType = PFD_MAIN_PLANE;

	int format = ChoosePixelFormat(_MainWindow._HDC, &pfd);

	if (format == 0)
	{
		_Result->Message("ChoosePixelFormat failed");
		return;
	}

	if (!SetPixelFormat(_MainWindow._HDC, format, &pfd))
	{
		_Result->Message("SetPixelFormat failed");
		return;
	}

	_HGLRC = wglCreateContext(_MainWindow._HDC);

	if (_HGLRC == NULL)
	{
		_Result->Message("wglCreateContext failed");
		return;
	}

	if (!wglMakeCurrent(_MainWindow._HDC, _HGLRC))
	{
		_Result->Message("wglMakeCurrent failed");
		return;
	}
}

LDL_WindowOpenGL1::~LDL_WindowOpenGL1()
{
	wglMakeCurrent(NULL, NULL);
	wglDeleteContext(_HGLRC);
}

bool LDL_WindowOpenGL1::Running()
{
	return _MainWindow.Running();
}

void LDL_WindowOpenGL1::Present()
{
	if (!SwapBuffers(_MainWindow._HDC))
	{
		_Result->Message("SwapBuffers failed");
	}

	Update();
}

void LDL_WindowOpenGL1::PollEvents()
{
	_MainWindow.PollEvents();
}

const LDL_Vec2i& LDL_WindowOpenGL1::Size()
{
	return _MainWindow.Size();
}

const LDL_Vec2i& LDL_WindowOpenGL1::Pos()
{
	return _MainWindow.Pos();
}

bool LDL_WindowOpenGL1::GetEvent(LDL_Event& event)
{
	return _MainWindow.GetEvent(event);
}

bool LDL_WindowOpenGL1::WaitEvent(LDL_Event& event)
{
	return _MainWindow.WaitEvent(event);
}

void LDL_WindowOpenGL1::StopEvent()
{
	_MainWindow.StopEvent();
}

const char* LDL_WindowOpenGL1::Title()
{
	return _MainWindow.Title();
}

void LDL_WindowOpenGL1::Title(const char* title)
{
	_MainWindow.Title(title);
}

void* LDL_WindowOpenGL1::NativeHandle()
{
	return _MainWindow._HWND;
}

void LDL_WindowOpenGL1::Update()
{
	_MainWindow.Update();
}