#ifndef LDL_OpenGL_OpenGL4_1_hpp
#define LDL_OpenGL_OpenGL4_1_hpp

#include <LDL/OpenGL/OpenGL4_0.hpp>

#ifdef __cplusplus
extern "C" {
#endif

typedef void (LDL_OPENGL_API_CALL PFNGLRELEASESHADERCOMPILERPROC)(void);
typedef void (LDL_OPENGL_API_CALL PFNGLSHADERBINARYPROC)(GLsizei count, const GLuint* shaders, GLenum binaryFormat, const void* binary, GLsizei length);
typedef void (LDL_OPENGL_API_CALL PFNGLGETSHADERPRECISIONFORMATPROC)(GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision);
typedef void (LDL_OPENGL_API_CALL PFNGLDEPTHRANGEFPROC)(GLfloat n, GLfloat f);
typedef void (LDL_OPENGL_API_CALL PFNGLCLEARDEPTHFPROC)(GLfloat d);
typedef void (LDL_OPENGL_API_CALL PFNGLGETPROGRAMBINARYPROC)(GLuint program, GLsizei bufSize, GLsizei* length, GLenum* binaryFormat, void* binary);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMBINARYPROC)(GLuint program, GLenum binaryFormat, const void* binary, GLsizei length);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMPARAMETERIPROC)(GLuint program, GLenum pname, GLint value);
typedef void (LDL_OPENGL_API_CALL PFNGLUSEPROGRAMSTAGESPROC)(GLuint pipeline, GLbitfield stages, GLuint program);
typedef void (LDL_OPENGL_API_CALL PFNGLACTIVESHADERPROGRAMPROC)(GLuint pipeline, GLuint program);
typedef GLuint(LDL_OPENGL_API_CALL PFNGLCREATESHADERPROGRAMVPROC)(GLenum type, GLsizei count, const GLchar* const* strings);
typedef void (LDL_OPENGL_API_CALL PFNGLBINDPROGRAMPIPELINEPROC)(GLuint pipeline);
typedef void (LDL_OPENGL_API_CALL PFNGLDELETEPROGRAMPIPELINESPROC)(GLsizei n, const GLuint* pipelines);
typedef void (LDL_OPENGL_API_CALL PFNGLGENPROGRAMPIPELINESPROC)(GLsizei n, GLuint* pipelines);
typedef GLboolean(LDL_OPENGL_API_CALL PFNGLISPROGRAMPIPELINEPROC)(GLuint pipeline);
typedef void (LDL_OPENGL_API_CALL PFNGLGETPROGRAMPIPELINEIVPROC)(GLuint pipeline, GLenum pname, GLint* params);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM1IPROC)(GLuint program, GLint location, GLint v0);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM1IVPROC)(GLuint program, GLint location, GLsizei count, const GLint* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM1FPROC)(GLuint program, GLint location, GLfloat v0);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM1FVPROC)(GLuint program, GLint location, GLsizei count, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM1DPROC)(GLuint program, GLint location, GLdouble v0);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM1DVPROC)(GLuint program, GLint location, GLsizei count, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM1UIPROC)(GLuint program, GLint location, GLuint v0);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM1UIVPROC)(GLuint program, GLint location, GLsizei count, const GLuint* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM2IPROC)(GLuint program, GLint location, GLint v0, GLint v1);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM2IVPROC)(GLuint program, GLint location, GLsizei count, const GLint* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM2FPROC)(GLuint program, GLint location, GLfloat v0, GLfloat v1);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM2FVPROC)(GLuint program, GLint location, GLsizei count, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM2DPROC)(GLuint program, GLint location, GLdouble v0, GLdouble v1);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM2DVPROC)(GLuint program, GLint location, GLsizei count, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM2UIPROC)(GLuint program, GLint location, GLuint v0, GLuint v1);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM2UIVPROC)(GLuint program, GLint location, GLsizei count, const GLuint* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM3IPROC)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM3IVPROC)(GLuint program, GLint location, GLsizei count, const GLint* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM3FPROC)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM3FVPROC)(GLuint program, GLint location, GLsizei count, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM3DPROC)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM3DVPROC)(GLuint program, GLint location, GLsizei count, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM3UIPROC)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM3UIVPROC)(GLuint program, GLint location, GLsizei count, const GLuint* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM4IPROC)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM4IVPROC)(GLuint program, GLint location, GLsizei count, const GLint* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM4FPROC)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM4FVPROC)(GLuint program, GLint location, GLsizei count, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM4DPROC)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2, GLdouble v3);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM4DVPROC)(GLuint program, GLint location, GLsizei count, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM4UIPROC)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORM4UIVPROC)(GLuint program, GLint location, GLsizei count, const GLuint* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX2FVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX3FVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX4FVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX2DVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX3DVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX4DVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble* value);
typedef void (LDL_OPENGL_API_CALL PFNGLVALIDATEPROGRAMPIPELINEPROC)(GLuint pipeline);
typedef void (LDL_OPENGL_API_CALL PFNGLGETPROGRAMPIPELINEINFOLOGPROC)(GLuint pipeline, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
typedef void (LDL_OPENGL_API_CALL PFNGLVERTEXATTRIBL1DPROC)(GLuint index, GLdouble x);
typedef void (LDL_OPENGL_API_CALL PFNGLVERTEXATTRIBL2DPROC)(GLuint index, GLdouble x, GLdouble y);
typedef void (LDL_OPENGL_API_CALL PFNGLVERTEXATTRIBL3DPROC)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
typedef void (LDL_OPENGL_API_CALL PFNGLVERTEXATTRIBL4DPROC)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
typedef void (LDL_OPENGL_API_CALL PFNGLVERTEXATTRIBL1DVPROC)(GLuint index, const GLdouble* v);
typedef void (LDL_OPENGL_API_CALL PFNGLVERTEXATTRIBL2DVPROC)(GLuint index, const GLdouble* v);
typedef void (LDL_OPENGL_API_CALL PFNGLVERTEXATTRIBL3DVPROC)(GLuint index, const GLdouble* v);
typedef void (LDL_OPENGL_API_CALL PFNGLVERTEXATTRIBL4DVPROC)(GLuint index, const GLdouble* v);
typedef void (LDL_OPENGL_API_CALL PFNGLVERTEXATTRIBLPOINTERPROC)(GLuint index, GLint size, GLenum type, GLsizei stride, const void* pointer);
typedef void (LDL_OPENGL_API_CALL PFNGLGETVERTEXATTRIBLDVPROC)(GLuint index, GLenum pname, GLdouble* params);
typedef void (LDL_OPENGL_API_CALL PFNGLVIEWPORTARRAYVPROC)(GLuint first, GLsizei count, const GLfloat* v);
typedef void (LDL_OPENGL_API_CALL PFNGLVIEWPORTINDEXEDFPROC)(GLuint index, GLfloat x, GLfloat y, GLfloat w, GLfloat h);
typedef void (LDL_OPENGL_API_CALL PFNGLVIEWPORTINDEXEDFVPROC)(GLuint index, const GLfloat* v);
typedef void (LDL_OPENGL_API_CALL PFNGLSCISSORARRAYVPROC)(GLuint first, GLsizei count, const GLint* v);
typedef void (LDL_OPENGL_API_CALL PFNGLSCISSORINDEXEDPROC)(GLuint index, GLint left, GLint bottom, GLsizei width, GLsizei height);
typedef void (LDL_OPENGL_API_CALL PFNGLSCISSORINDEXEDVPROC)(GLuint index, const GLint* v);
typedef void (LDL_OPENGL_API_CALL PFNGLDEPTHRANGEARRAYVPROC)(GLuint first, GLsizei count, const GLdouble* v);
typedef void (LDL_OPENGL_API_CALL PFNGLDEPTHRANGEINDEXEDPROC)(GLuint index, GLdouble n, GLdouble f);
typedef void (LDL_OPENGL_API_CALL PFNGLGETFLOATI_VPROC)(GLenum target, GLuint index, GLfloat* data);
typedef void (LDL_OPENGL_API_CALL PFNGLGETDOUBLEI_VPROC)(GLenum target, GLuint index, GLdouble* data);

LDL_OPENGL_API_ENTRY PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler;
LDL_OPENGL_API_ENTRY PFNGLSHADERBINARYPROC glShaderBinary;
LDL_OPENGL_API_ENTRY PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat;
LDL_OPENGL_API_ENTRY PFNGLDEPTHRANGEFPROC glDepthRangef;
LDL_OPENGL_API_ENTRY PFNGLCLEARDEPTHFPROC glClearDepthf;
LDL_OPENGL_API_ENTRY PFNGLGETPROGRAMBINARYPROC glGetProgramBinary;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMBINARYPROC glProgramBinary;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMPARAMETERIPROC glProgramParameteri;
LDL_OPENGL_API_ENTRY PFNGLUSEPROGRAMSTAGESPROC glUseProgramStages;
LDL_OPENGL_API_ENTRY PFNGLACTIVESHADERPROGRAMPROC glActiveShaderProgram;
LDL_OPENGL_API_ENTRY PFNGLCREATESHADERPROGRAMVPROC glCreateShaderProgramv;
LDL_OPENGL_API_ENTRY PFNGLBINDPROGRAMPIPELINEPROC glBindProgramPipeline;
LDL_OPENGL_API_ENTRY PFNGLDELETEPROGRAMPIPELINESPROC glDeleteProgramPipelines;
LDL_OPENGL_API_ENTRY PFNGLGENPROGRAMPIPELINESPROC glGenProgramPipelines;
LDL_OPENGL_API_ENTRY PFNGLISPROGRAMPIPELINEPROC glIsProgramPipeline;
LDL_OPENGL_API_ENTRY PFNGLGETPROGRAMPIPELINEIVPROC glGetProgramPipelineiv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM1IPROC glProgramUniform1i;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM1IVPROC glProgramUniform1iv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM1FVPROC glProgramUniform1fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM1DPROC glProgramUniform1d;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM1DVPROC glProgramUniform1dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM1UIPROC glProgramUniform1ui;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM1UIVPROC glProgramUniform1uiv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM2IPROC glProgramUniform2i;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM2IVPROC glProgramUniform2iv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM2FVPROC glProgramUniform2fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM2DPROC glProgramUniform2d;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM2DVPROC glProgramUniform2dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM2UIPROC glProgramUniform2ui;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM2UIVPROC glProgramUniform2uiv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM3IPROC glProgramUniform3i;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM3IVPROC glProgramUniform3iv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM3FVPROC glProgramUniform3fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM3DPROC glProgramUniform3d;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM3DVPROC glProgramUniform3dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM3UIPROC glProgramUniform3ui;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM3UIVPROC glProgramUniform3uiv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM4IPROC glProgramUniform4i;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM4IVPROC glProgramUniform4iv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM4FVPROC glProgramUniform4fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM4DPROC glProgramUniform4d;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM4DVPROC glProgramUniform4dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM4UIPROC glProgramUniform4ui;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORM4UIVPROC glProgramUniform4uiv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX2FVPROC glProgramUniformMatrix2fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX2DVPROC glProgramUniformMatrix2dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX3DVPROC glProgramUniformMatrix3dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX4DVPROC glProgramUniformMatrix4dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC glProgramUniformMatrix2x3fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC glProgramUniformMatrix3x2fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC glProgramUniformMatrix2x4fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC glProgramUniformMatrix4x2fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC glProgramUniformMatrix3x4fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC glProgramUniformMatrix4x3fv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC glProgramUniformMatrix2x3dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC glProgramUniformMatrix3x2dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC glProgramUniformMatrix2x4dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC glProgramUniformMatrix4x2dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC glProgramUniformMatrix3x4dv;
LDL_OPENGL_API_ENTRY PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC glProgramUniformMatrix4x3dv;
LDL_OPENGL_API_ENTRY PFNGLVALIDATEPROGRAMPIPELINEPROC glValidateProgramPipeline;
LDL_OPENGL_API_ENTRY PFNGLGETPROGRAMPIPELINEINFOLOGPROC glGetProgramPipelineInfoLog;
LDL_OPENGL_API_ENTRY PFNGLVERTEXATTRIBL1DPROC glVertexAttribL1d;
LDL_OPENGL_API_ENTRY PFNGLVERTEXATTRIBL2DPROC glVertexAttribL2d;
LDL_OPENGL_API_ENTRY PFNGLVERTEXATTRIBL3DPROC glVertexAttribL3d;
LDL_OPENGL_API_ENTRY PFNGLVERTEXATTRIBL4DPROC glVertexAttribL4d;
LDL_OPENGL_API_ENTRY PFNGLVERTEXATTRIBL1DVPROC glVertexAttribL1dv;
LDL_OPENGL_API_ENTRY PFNGLVERTEXATTRIBL2DVPROC glVertexAttribL2dv;
LDL_OPENGL_API_ENTRY PFNGLVERTEXATTRIBL3DVPROC glVertexAttribL3dv;
LDL_OPENGL_API_ENTRY PFNGLVERTEXATTRIBL4DVPROC glVertexAttribL4dv;
LDL_OPENGL_API_ENTRY PFNGLVERTEXATTRIBLPOINTERPROC glVertexAttribLPointer;
LDL_OPENGL_API_ENTRY PFNGLGETVERTEXATTRIBLDVPROC glGetVertexAttribLdv;
LDL_OPENGL_API_ENTRY PFNGLVIEWPORTARRAYVPROC glViewportArrayv;
LDL_OPENGL_API_ENTRY PFNGLVIEWPORTINDEXEDFPROC glViewportIndexedf;
LDL_OPENGL_API_ENTRY PFNGLVIEWPORTINDEXEDFVPROC glViewportIndexedfv;
LDL_OPENGL_API_ENTRY PFNGLSCISSORARRAYVPROC glScissorArrayv;
LDL_OPENGL_API_ENTRY PFNGLSCISSORINDEXEDPROC glScissorIndexed;
LDL_OPENGL_API_ENTRY PFNGLSCISSORINDEXEDVPROC glScissorIndexedv;
LDL_OPENGL_API_ENTRY PFNGLDEPTHRANGEARRAYVPROC glDepthRangeArrayv;
LDL_OPENGL_API_ENTRY PFNGLDEPTHRANGEINDEXEDPROC glDepthRangeIndexed;
LDL_OPENGL_API_ENTRY PFNGLGETFLOATI_VPROC glGetFloati_v;
LDL_OPENGL_API_ENTRY PFNGLGETDOUBLEI_VPROC glGetDoublei_v;

#ifdef __cplusplus
}
#endif

#endif 