#ifndef LDL_OpenGL_OpenGL1_5_hpp
#define LDL_OpenGL_OpenGL1_5_hpp

#include <LDL/OpenGL/OpenGL1_4.hpp>

#ifdef __cplusplus
extern "C" {
#endif

typedef void (OPENGL_API_CALL PFNGLGENQUERIESPROC)(GLsizei n, GLuint* ids);
typedef void (OPENGL_API_CALL PFNGLDELETEQUERIESPROC)(GLsizei n, const GLuint* ids);
typedef GLboolean(OPENGL_API_CALL PFNGLISQUERYPROC)(GLuint id);
typedef void (OPENGL_API_CALL PFNGLBEGINQUERYPROC)(GLenum target, GLuint id);
typedef void (OPENGL_API_CALL PFNGLENDQUERYPROC)(GLenum target);
typedef void (OPENGL_API_CALL PFNGLGETQUERYIVPROC)(GLenum target, GLenum pname, GLint* params);
typedef void (OPENGL_API_CALL PFNGLGETQUERYOBJECTIVPROC)(GLuint id, GLenum pname, GLint* params);
typedef void (OPENGL_API_CALL PFNGLGETQUERYOBJECTUIVPROC)(GLuint id, GLenum pname, GLuint* params);
typedef void (OPENGL_API_CALL PFNGLBINDBUFFERPROC)(GLenum target, GLuint buffer);
typedef void (OPENGL_API_CALL PFNGLDELETEBUFFERSPROC)(GLsizei n, const GLuint* buffers);
typedef void (OPENGL_API_CALL PFNGLGENBUFFERSPROC)(GLsizei n, GLuint* buffers);
typedef GLboolean(OPENGL_API_CALL PFNGLISBUFFERPROC)(GLuint buffer);
typedef void (OPENGL_API_CALL PFNGLBUFFERDATAPROC)(GLenum target, GLsizeiptr size, const void* data, GLenum usage);
typedef void (OPENGL_API_CALL PFNGLBUFFERSUBDATAPROC)(GLenum target, GLintptr offset, GLsizeiptr size, const void* data);
typedef void (OPENGL_API_CALL PFNGLGETBUFFERSUBDATAPROC)(GLenum target, GLintptr offset, GLsizeiptr size, void* data);
typedef void* (OPENGL_API_CALL PFNGLMAPBUFFERPROC)(GLenum target, GLenum access);
typedef GLboolean(OPENGL_API_CALL PFNGLUNMAPBUFFERPROC)(GLenum target);
typedef void (OPENGL_API_CALL PFNGLGETBUFFERPARAMETERIVPROC)(GLenum target, GLenum pname, GLint* params);
typedef void (OPENGL_API_CALL PFNGLGETBUFFERPOINTERVPROC)(GLenum target, GLenum pname, void** params);

OPENGL_API_ENTRY PFNGLGENQUERIESPROC glGenQueries;
OPENGL_API_ENTRY PFNGLDELETEQUERIESPROC glDeleteQueries;
OPENGL_API_ENTRY PFNGLISQUERYPROC glIsQuery;
OPENGL_API_ENTRY PFNGLBEGINQUERYPROC glBeginQuery;
OPENGL_API_ENTRY PFNGLENDQUERYPROC glEndQuery;
OPENGL_API_ENTRY PFNGLGETQUERYIVPROC glGetQueryiv;
OPENGL_API_ENTRY PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv;
OPENGL_API_ENTRY PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv;
OPENGL_API_ENTRY PFNGLBINDBUFFERPROC glBindBuffer;
OPENGL_API_ENTRY PFNGLDELETEBUFFERSPROC glDeleteBuffers;
OPENGL_API_ENTRY PFNGLGENBUFFERSPROC glGenBuffers;
OPENGL_API_ENTRY PFNGLISBUFFERPROC glIsBuffer;
OPENGL_API_ENTRY PFNGLBUFFERDATAPROC glBufferData;
OPENGL_API_ENTRY PFNGLBUFFERSUBDATAPROC glBufferSubData;
OPENGL_API_ENTRY PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData;
OPENGL_API_ENTRY PFNGLMAPBUFFERPROC glMapBuffer;
OPENGL_API_ENTRY PFNGLUNMAPBUFFERPROC glUnmapBuffer;
OPENGL_API_ENTRY PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv;
OPENGL_API_ENTRY PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv;

#ifdef __cplusplus
}
#endif

#endif     