#ifndef LDL_OpenGL_OpenGL1_4_hpp
#define LDL_OpenGL_OpenGL1_4_hpp

#include <LDL/OpenGL/OpenGL1_3.hpp>

#ifdef __cplusplus
extern "C" {
#endif

typedef void (LDL_OPENGL_API_CALL PFNGLBLENDFUNCSEPARATEPROC)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
typedef void (LDL_OPENGL_API_CALL PFNGLMULTIDRAWARRAYSPROC)(GLenum mode, const GLint* first, const GLsizei* count, GLsizei drawcount);
typedef void (LDL_OPENGL_API_CALL PFNGLMULTIDRAWELEMENTSPROC)(GLenum mode, const GLsizei* count, GLenum type, const void* const* indices, GLsizei drawcount);
typedef void (LDL_OPENGL_API_CALL PFNGLPOINTPARAMETERFPROC)(GLenum pname, GLfloat param);
typedef void (LDL_OPENGL_API_CALL PFNGLPOINTPARAMETERFVPROC)(GLenum pname, const GLfloat* params);
typedef void (LDL_OPENGL_API_CALL PFNGLPOINTPARAMETERIPROC)(GLenum pname, GLint param);
typedef void (LDL_OPENGL_API_CALL PFNGLPOINTPARAMETERIVPROC)(GLenum pname, const GLint* params);
typedef void (LDL_OPENGL_API_CALL PFNGLFOGCOORDFPROC)(GLfloat coord);
typedef void (LDL_OPENGL_API_CALL PFNGLFOGCOORDFVPROC)(const GLfloat* coord);
typedef void (LDL_OPENGL_API_CALL PFNGLFOGCOORDDPROC)(GLdouble coord);
typedef void (LDL_OPENGL_API_CALL PFNGLFOGCOORDDVPROC)(const GLdouble* coord);
typedef void (LDL_OPENGL_API_CALL PFNGLFOGCOORDPOINTERPROC)(GLenum type, GLsizei stride, const void* pointer);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3BPROC)(GLbyte red, GLbyte green, GLbyte blue);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3BVPROC)(const GLbyte* v);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3DPROC)(GLdouble red, GLdouble green, GLdouble blue);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3DVPROC)(const GLdouble* v);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3FPROC)(GLfloat red, GLfloat green, GLfloat blue);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3FVPROC)(const GLfloat* v);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3IPROC)(GLint red, GLint green, GLint blue);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3IVPROC)(const GLint* v);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3SPROC)(GLshort red, GLshort green, GLshort blue);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3SVPROC)(const GLshort* v);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3UBPROC)(GLubyte red, GLubyte green, GLubyte blue);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3UBVPROC)(const GLubyte* v);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3UIPROC)(GLuint red, GLuint green, GLuint blue);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3UIVPROC)(const GLuint* v);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3USPROC)(GLushort red, GLushort green, GLushort blue);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLOR3USVPROC)(const GLushort* v);
typedef void (LDL_OPENGL_API_CALL PFNGLSECONDARYCOLORPOINTERPROC)(GLint size, GLenum type, GLsizei stride, const void* pointer);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS2DPROC)(GLdouble x, GLdouble y);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS2DVPROC)(const GLdouble* v);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS2FPROC)(GLfloat x, GLfloat y);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS2FVPROC)(const GLfloat* v);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS2IPROC)(GLint x, GLint y);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS2IVPROC)(const GLint* v);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS2SPROC)(GLshort x, GLshort y);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS2SVPROC)(const GLshort* v);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS3DPROC)(GLdouble x, GLdouble y, GLdouble z);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS3DVPROC)(const GLdouble* v);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS3FPROC)(GLfloat x, GLfloat y, GLfloat z);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS3FVPROC)(const GLfloat* v);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS3IPROC)(GLint x, GLint y, GLint z);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS3IVPROC)(const GLint* v);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS3SPROC)(GLshort x, GLshort y, GLshort z);
typedef void (LDL_OPENGL_API_CALL PFNGLWINDOWPOS3SVPROC)(const GLshort* v);
typedef void (LDL_OPENGL_API_CALL PFNGLBLENDCOLORPROC)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
typedef void (LDL_OPENGL_API_CALL PFNGLBLENDEQUATIONPROC)(GLenum mode);

LDL_OPENGL_API_ENTRY PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate;
LDL_OPENGL_API_ENTRY PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays;
LDL_OPENGL_API_ENTRY PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements;
LDL_OPENGL_API_ENTRY PFNGLPOINTPARAMETERFPROC glPointParameterf;
LDL_OPENGL_API_ENTRY PFNGLPOINTPARAMETERFVPROC glPointParameterfv;
LDL_OPENGL_API_ENTRY PFNGLPOINTPARAMETERIPROC glPointParameteri;
LDL_OPENGL_API_ENTRY PFNGLPOINTPARAMETERIVPROC glPointParameteriv;
LDL_OPENGL_API_ENTRY PFNGLFOGCOORDFPROC glFogCoordf;
LDL_OPENGL_API_ENTRY PFNGLFOGCOORDFVPROC glFogCoordfv;
LDL_OPENGL_API_ENTRY PFNGLFOGCOORDDPROC glFogCoordd;
LDL_OPENGL_API_ENTRY PFNGLFOGCOORDDVPROC glFogCoorddv;
LDL_OPENGL_API_ENTRY PFNGLFOGCOORDPOINTERPROC glFogCoordPointer;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3BPROC glSecondaryColor3b;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3BVPROC glSecondaryColor3bv;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3DPROC glSecondaryColor3d;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3DVPROC glSecondaryColor3dv;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3FPROC glSecondaryColor3f;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3FVPROC glSecondaryColor3fv;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3IPROC glSecondaryColor3i;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3IVPROC glSecondaryColor3iv;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3SPROC glSecondaryColor3s;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3SVPROC glSecondaryColor3sv;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3UBPROC glSecondaryColor3ub;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3UBVPROC glSecondaryColor3ubv;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3UIPROC glSecondaryColor3ui;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3UIVPROC glSecondaryColor3uiv;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3USPROC glSecondaryColor3us;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLOR3USVPROC glSecondaryColor3usv;
LDL_OPENGL_API_ENTRY PFNGLSECONDARYCOLORPOINTERPROC glSecondaryColorPointer;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS2DPROC glWindowPos2d;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS2DVPROC glWindowPos2dv;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS2FPROC glWindowPos2f;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS2FVPROC glWindowPos2fv;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS2IPROC glWindowPos2i;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS2IVPROC glWindowPos2iv;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS2SPROC glWindowPos2s;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS2SVPROC glWindowPos2sv;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS3DPROC glWindowPos3d;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS3DVPROC glWindowPos3dv;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS3FPROC glWindowPos3f;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS3FVPROC glWindowPos3fv;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS3IPROC glWindowPos3i;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS3IVPROC glWindowPos3iv;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS3SPROC glWindowPos3s;
LDL_OPENGL_API_ENTRY PFNGLWINDOWPOS3SVPROC glWindowPos3sv;
LDL_OPENGL_API_ENTRY PFNGLBLENDCOLORPROC glBlendColor;
LDL_OPENGL_API_ENTRY PFNGLBLENDEQUATIONPROC glBlendEquation;

#ifdef __cplusplus
}
#endif

#endif     