call "C:\Downloads\codeblocks-12.11mingw-setup\MinGW\mingwvars.bat"

g++ -Wall -Wextra -pedantic -O2 -std=c++98 -s -shared -o LDL_MinGW.dll -DFT2_BUILD_LIBRARY -DLDL_SHARED_LIBRARY ^
..\source\Shared\Allocators\*.cpp ^
..\source\Shared\Core\*.cpp ^
..\source\Shared\Events\*.cpp ^
..\source\Shared\Time\*.cpp ^
..\source\Shared\Audio\*.cpp ^
..\source\Shared\Graphics\*.cpp ^
..\source\Shared\Graphics\Base\*.cpp ^
..\source\Shared\Graphics\Creators\*.cpp ^
..\source\Shared\Graphics\Renders\Software\*.cpp ^
..\source\Shared\Graphics\Renders\OpenGL\*.cpp ^
..\source\Shared\Graphics\Renders\OpenGL1\*.cpp ^
..\source\Shared\Graphics\Renders\OpenGL3\*.cpp ^
..\source\Shared\Graphics\Primitives\*.cpp ^
..\source\Shared\Graphics\Utils\*.cpp ^
..\source\Shared\Loaders\*.cpp ^
..\source\Shared\OpenGL\*.cpp ^
..\source\Shared\GLU\*.cpp ^
..\source\Shared\GLUT\*.cpp ^
..\source\Shared\LDLC\*.cpp ^
..\source\Shared\Text\*.cpp ^
..\source\Platforms\Windows\DirectX\*.cpp ^
..\source\Platforms\Windows\Graphics\*.cpp ^
..\source\Platforms\Windows\Graphics\OpenGL\*.cpp ^
..\source\Platforms\Windows\Graphics\OpenGL1\*.cpp ^
..\source\Platforms\Windows\Graphics\OpenGL3\*.cpp ^
..\source\Platforms\Windows\Graphics\Software\*.cpp ^
..\source\Platforms\Windows\Time\Ticks.cpp ^
..\source\Platforms\Windows\Core\*.cpp ^
..\source\Platforms\Windows\Input\*.cpp ^
..\source\Platforms\Windows\Audio\DirectSound8\*.cpp ^
..\dependencies\freetype\src\sfnt\sfdriver.c ^
..\dependencies\freetype\src\sfnt\ttcmap.c ^
..\dependencies\freetype\src\sfnt\ttsbit.c ^
..\dependencies\freetype\src\sfnt\ttcolr.c ^
..\dependencies\freetype\src\sfnt\ttcpal.c ^
..\dependencies\freetype\src\sfnt\ttsvg.c ^
..\dependencies\freetype\src\sfnt\ttload.c ^
..\dependencies\freetype\src\sfnt\ttkern.c ^
..\dependencies\freetype\src\sfnt\ttmtx.c ^
..\dependencies\freetype\src\sfnt\ttpost.c ^
..\dependencies\freetype\src\sfnt\sfobjs.c ^
..\dependencies\freetype\src\sfnt\ttbdf.c ^
..\dependencies\freetype\src\sfnt\sfwoff.c ^
..\dependencies\freetype\src\base\ftglyph.c ^
..\dependencies\freetype\src\base\ftcid.c ^
..\dependencies\freetype\src\base\ftbitmap.c ^
..\dependencies\freetype\src\base\ftfstype.c ^
..\dependencies\freetype\src\base\ftgxval.c ^
..\dependencies\freetype\src\base\ftbbox.c ^
..\dependencies\freetype\src\base\ftbdf.c ^
..\dependencies\freetype\src\base\ftpatent.c ^
..\dependencies\freetype\src\base\ftmm.c ^
..\dependencies\freetype\src\base\ftgasp.c ^
..\dependencies\freetype\src\autofit\autofit.c ^
..\dependencies\freetype\src\base\ftotval.c ^
..\dependencies\freetype\src\base\ftinit.c ^
..\dependencies\freetype\src\base\ftbase.c ^
..\dependencies\freetype\src\base\ftwinfnt.c ^
..\dependencies\freetype\src\base\ftsynth.c ^
..\dependencies\freetype\src\base\fttype1.c ^
..\dependencies\freetype\src\base\ftstroke.c ^
..\dependencies\freetype\src\base\ftpfr.c ^
..\dependencies\freetype\src\bzip2\ftbzip2.c ^
..\dependencies\freetype\src\pcf\pcf.c ^
..\dependencies\freetype\src\cid\type1cid.c ^
..\dependencies\freetype\src\gzip\ftgzip.c ^
..\dependencies\freetype\src\bdf\bdf.c ^
..\dependencies\freetype\src\lzw\ftlzw.c ^
..\dependencies\freetype\src\cff\cff.c ^
..\dependencies\freetype\src\pfr\pfr.c ^
..\dependencies\freetype\src\cache\ftcache.c ^
..\dependencies\freetype\src\raster\raster.c ^
..\dependencies\freetype\src\pshinter\pshinter.c ^
..\dependencies\freetype\src\smooth\smooth.c ^
..\dependencies\freetype\src\svg\svg.c ^
..\dependencies\freetype\src\sdf\sdf.c ^
..\dependencies\freetype\src\type42\type42.c ^
..\dependencies\freetype\src\winfonts\winfnt.c ^
..\dependencies\freetype\builds\windows\ftdebug.c ^
..\dependencies\freetype\builds\windows\ftsystem.c ^
..\dependencies\freetype\src\psnames\psnames.c ^
..\dependencies\freetype\src\truetype\truetype.c ^
..\dependencies\freetype\src\psaux\psaux.c ^
..\dependencies\freetype\src\type1\type1.c ^
-I..\include\ ^
-I..\dependencies\dx9sdk\Include ^
-I..\dependencies\freetype\include ^
-lgdi32 ^
-lopengl32 ^
-lwinmm ^
-Wl,--out-implib,LDL_MinGW.lib