/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_Core_MemoryManager_hpp
#define LDL_Core_MemoryManager_hpp

#include <LDL/std/stddef.hpp>

namespace LDL
{
	namespace Core
	{
		typedef void* (*mallocFunc) (size_t size);
		typedef void* (*callocFunc) (size_t nmemb, size_t size);
		typedef void* (*reallocFunc)(void* mem, size_t size);
		typedef void  (*freeFunc)   (void* mem);

		class MemoryManager
		{
		public:
			static MemoryManager& Instance();
			bool Functions(mallocFunc malloc_func, callocFunc calloc_func, reallocFunc realloc_func, freeFunc free_func);
			mallocFunc  GetMalloc();
			callocFunc  GetCalloc();
			reallocFunc GetRealloc();
			freeFunc    GetFree();
		private:
			enum
			{
				SizeOf = 64
			};

			MemoryManager();
			~MemoryManager();

			MemoryManager(const MemoryManager&);
			MemoryManager& operator=(const MemoryManager&);

			mallocFunc  _mallocFunc;
			callocFunc  _callocFunc;
			reallocFunc _reallocFunc;
			freeFunc    _freeFunc;

			static MemoryManager* _instance;
			static char _bytes[SizeOf];
		};
	}
}

#endif
