#include <LDL/OpenGL/OpenGL3_3.hpp>

PFNGLCREATESHADERPROC      * glCreateShader      = NULL;
PFNGLSHADERSOURCEPROC      * glShaderSource      = NULL;
PFNGLCOMPILESHADERPROC     * glCompileShader     = NULL;
PFNGLGETSHADERIVPROC       * glGetShaderiv       = NULL;
PFNGLGETSHADERINFOLOGPROC  * glGetShaderInfoLog  = NULL;
PFNGLCREATEPROGRAMPROC     * glCreateProgram     = NULL;
PFNGLATTACHSHADERPROC      * glAttachShader      = NULL;
PFNGLLINKPROGRAMPROC       * glLinkProgram       = NULL;
PFNGLGETPROGRAMIVPROC      * glGetProgramiv      = NULL;
PFNGLGETPROGRAMINFOLOGPROC * glGetProgramInfoLog = NULL;
PFNGLDELETESHADERPROC      * glDeleteShader      = NULL;
PFNGLGENVERTEXARRAYSPROC* glGenVertexArrays = NULL;
PFNGLGENBUFFERSARBPROC* glGenBuffers = NULL;
PFNGLBINDVERTEXARRAYPROC* glBindVertexArray = NULL;
PFNGLBINDBUFFERPROC* glBindBuffer = NULL;
PFNGLBUFFERDATAPROC* glBufferData = NULL;
PFNGLVERTEXATTRIBPOINTERPROC* glVertexAttribPointer = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC* glEnableVertexAttribArray = NULL;
PFNGLUSEPROGRAMPROC* glUseProgram = NULL;
PFNGLUNIFORM1IPROC* glUniform1i = NULL;

PFNGLGETUNIFORMLOCATIONPROC* glGetUniformLocation = NULL;
PFNGLDELETEVERTEXARRAYSPROC* glDeleteVertexArrays = NULL;
PFNGLDELETEBUFFERSPROC* glDeleteBuffers = NULL;
PFNGLGENERATEMIPMAPPROC* glGenerateMipmap = NULL;
PFNGLACTIVETEXTUREPROC* glActiveTexture = NULL;

PFNGLUNIFORMMATRIX2FVPROC* glUniformMatrix2fv = NULL;
PFNGLUNIFORMMATRIX3FVPROC* glUniformMatrix3fv = NULL;
PFNGLUNIFORMMATRIX4FVPROC* glUniformMatrix4fv = NULL;

PFNGLUNIFORM1FVPROC* glUniform1fv = NULL;
PFNGLUNIFORM2FVPROC* glUniform2fv = NULL;
PFNGLUNIFORM3FVPROC* glUniform3fv = NULL;
PFNGLUNIFORM4FVPROC* glUniform4fv = NULL;

PFNGLUNIFORM1FPROC* glUniform1f = NULL;
PFNGLUNIFORM2FPROC* glUniform2f = NULL;
PFNGLUNIFORM3FPROC* glUniform3f = NULL;
PFNGLUNIFORM4FPROC* glUniform4f = NULL;