
call "C:\Program Files\Microsoft Visual Studio\VC98\Bin\VCVARS32.BAT"

CL /O2 /FeLDL_VC6.dll -LD -GX /I..\include /I..\source /I..\dependencies\freetype\include /DFT2_BUILD_LIBRARY /DLDL_SHARED_LIBRARY ^
..\source\LDL\Shared\Allocators\*.cpp ^
..\source\LDL\Shared\Core\*.cpp ^
..\source\LDL\Shared\Events\*.cpp ^
..\source\LDL\Shared\Time\*.cpp ^
..\source\LDL\Shared\Audio\*.cpp ^
..\source\LDL\Shared\Graphics\*.cpp ^
..\source\LDL\Shared\Graphics\Base\*.cpp ^
..\source\LDL\Shared\Graphics\Creators\*.cpp ^
..\source\LDL\Shared\Graphics\Renders\Software\*.cpp ^
..\source\LDL\Shared\Graphics\Renders\OpenGL\*.cpp ^
..\source\LDL\Shared\Graphics\Renders\OpenGL1\*.cpp ^
..\source\LDL\Shared\Graphics\Renders\OpenGL3\*.cpp ^
..\source\LDL\Shared\Graphics\Renders\Glide\*.cpp ^
..\source\LDL\Shared\Graphics\Renders\Direct3D6\*.cpp ^
..\source\LDL\Shared\Loaders\*.cpp ^
..\source\LDL\Shared\APIs\OpenGL\*.cpp ^
..\source\LDL\Shared\APIs\DirectX\*.cpp ^
..\source\LDL\Shared\APIs\Glide\*.cpp ^
..\source\LDL\Shared\APIs\GLU\*.cpp ^
..\source\LDL\Shared\APIs\GLUT\*.cpp ^
..\source\LDL\Shared\APIs\LDLC\*.cpp ^
..\source\LDL\Shared\Text\*.cpp ^
..\source\LDL\Platforms\Windows\DirectX\*.cpp ^
..\source\LDL\Platforms\Windows\Graphics\*.cpp ^
..\source\LDL\Platforms\Windows\Time\Ticks.cpp ^
..\source\LDL\Platforms\Windows\Core\*.cpp ^
..\source\LDL\Platforms\Windows\Input\*.cpp ^
..\source\LDL\Platforms\Windows\Audio\DirectSound8\*.cpp ^
..\dependencies\freetype\src\sfnt\sfdriver.c ^
..\dependencies\freetype\src\sfnt\ttcmap.c ^
..\dependencies\freetype\src\sfnt\ttsbit.c ^
..\dependencies\freetype\src\sfnt\ttcolr.c ^
..\dependencies\freetype\src\sfnt\ttcpal.c ^
..\dependencies\freetype\src\sfnt\ttsvg.c ^
..\dependencies\freetype\src\sfnt\ttload.c ^
..\dependencies\freetype\src\sfnt\ttkern.c ^
..\dependencies\freetype\src\sfnt\ttmtx.c ^
..\dependencies\freetype\src\sfnt\ttpost.c ^
..\dependencies\freetype\src\sfnt\sfobjs.c ^
..\dependencies\freetype\src\sfnt\ttbdf.c ^
..\dependencies\freetype\src\sfnt\sfwoff.c ^
..\dependencies\freetype\src\base\ftglyph.c ^
..\dependencies\freetype\src\base\ftcid.c ^
..\dependencies\freetype\src\base\ftbitmap.c ^
..\dependencies\freetype\src\base\ftfstype.c ^
..\dependencies\freetype\src\base\ftgxval.c ^
..\dependencies\freetype\src\base\ftbbox.c ^
..\dependencies\freetype\src\base\ftbdf.c ^
..\dependencies\freetype\src\base\ftpatent.c ^
..\dependencies\freetype\src\base\ftmm.c ^
..\dependencies\freetype\src\base\ftgasp.c ^
..\dependencies\freetype\src\autofit\autofit.c ^
..\dependencies\freetype\src\base\ftotval.c ^
..\dependencies\freetype\src\base\ftinit.c ^
..\dependencies\freetype\src\base\ftbase.c ^
..\dependencies\freetype\src\base\ftwinfnt.c ^
..\dependencies\freetype\src\base\ftsynth.c ^
..\dependencies\freetype\src\base\fttype1.c ^
..\dependencies\freetype\src\base\ftstroke.c ^
..\dependencies\freetype\src\base\ftpfr.c ^
..\dependencies\freetype\src\bzip2\ftbzip2.c ^
..\dependencies\freetype\src\pcf\pcf.c ^
..\dependencies\freetype\src\cid\type1cid.c ^
..\dependencies\freetype\src\gzip\ftgzip.c ^
..\dependencies\freetype\src\bdf\bdf.c ^
..\dependencies\freetype\src\lzw\ftlzw.c ^
..\dependencies\freetype\src\cff\cff.c ^
..\dependencies\freetype\src\pfr\pfr.c ^
..\dependencies\freetype\src\cache\ftcache.c ^
..\dependencies\freetype\src\raster\raster.c ^
..\dependencies\freetype\src\pshinter\pshinter.c ^
..\dependencies\freetype\src\smooth\smooth.c ^
..\dependencies\freetype\src\svg\svg.c ^
..\dependencies\freetype\src\sdf\sdf.c ^
..\dependencies\freetype\src\type42\type42.c ^
..\dependencies\freetype\src\winfonts\winfnt.c ^
..\dependencies\freetype\builds\windows\ftdebug.c ^
..\dependencies\freetype\builds\windows\ftsystem.c ^
..\dependencies\freetype\src\psnames\psnames.c ^
..\dependencies\freetype\src\truetype\truetype.c ^
..\dependencies\freetype\src\psaux\psaux.c ^
..\dependencies\freetype\src\type1\type1.c ^
gdi32.lib ^
opengl32.lib ^
winmm.lib   ^
user32.lib

del *.obj