/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <LDL/Renders/SoftRndr.hpp>
#include <assert.h>
#include <string.h>

LDL_TextureSoftware::LDL_TextureSoftware(const LDL_Vec2i& size, uint8_t* pixels, uint8_t bpp) :
	_Surface(size, size, bpp)
{
	assert(size.x >= 0);
	assert(size.y >= 0);
	assert(pixels != NULL);
	assert(bpp >= 1 && bpp <= 4);

	memcpy(_Surface.Pixels(), pixels, size.x * size.y * bpp);
}

LDL_TextureSoftware::LDL_TextureSoftware(const LDL_Vec2i& size, uint8_t bpp) :
	_Surface(size, size, bpp)
{
	assert(size.x >= 0);
	assert(size.y >= 0);
	assert(bpp >= 1 && bpp <= 4);
}

LDL_TextureSoftware::~LDL_TextureSoftware()
{
}

void LDL_TextureSoftware::Copy(const LDL_Vec2i& dstPos, const LDL_Vec2i& srcSize, uint8_t* pixels, uint8_t bpp)
{
	assert(dstPos.x >= 0);
	assert(dstPos.y >= 0);
	assert(srcSize.x >= 0);
	assert(srcSize.y >= 0);
	assert(pixels != NULL);
	assert(bpp >= 1 && bpp <= 4);
}

void LDL_TextureSoftware::Copy(const LDL_Vec2i& dstPos, LDL_Surface* surface, const LDL_Vec2i& srcSize)
{
	assert(dstPos.x >= 0);
	assert(dstPos.y >= 0);
	assert(srcSize.x >= 0);
	assert(srcSize.y >= 0);
	assert(surface != NULL);
}

const LDL_Vec2i& LDL_TextureSoftware::Size()
{
	return _Size;
}

const LDL_Vec2i& LDL_TextureSoftware::Quad()
{
	return _Quad;
}

LDL_Surface* LDL_TextureSoftware::GetSurface()
{
	return &_Surface;
}

LDL_RenderSoftware::LDL_RenderSoftware(LDL_WindowSoftware* window, LDL_Palette* palette) :
	_Window(window),
	_BaseRender(_Window->Size(), palette),
	_Screen(_Window->Size(), _Window->Size(), _Window->GetBpp())
{
}

void LDL_RenderSoftware::Begin()
{
}

void LDL_RenderSoftware::End()
{
	_Window->Present(_Screen.Pixels(), _Screen.Bpp());
	_Window->Present();
}

void LDL_RenderSoftware::Line(const LDL_Vec2i& pos1, const LDL_Vec2i& pos2)
{
	assert(pos1.x >= 0);
	assert(pos1.y >= 0);

	assert(pos2.x >= 0);
	assert(pos2.y >= 0);
}

void LDL_RenderSoftware::Fill(const LDL_Vec2i& pos, const LDL_Vec2i& size)
{
	assert(size.x > 0);
	assert(size.y > 0);

	int x = pos.x;
	int y = pos.y;

	uint8_t* pixels = _Screen.Pixels();
	LDL_Color color = _BaseRender.Color();

	for (int i = 0; i < size.x; i++)
	{
		for (int j = 0; j < size.y; j++)
		{
			int idx = (_Screen.Size().x * (y + j) + (x + i)) * _Screen.Bpp();

#if defined(_WIN32)
			pixels[idx] = color.b;
			pixels[idx + 2] = color.r;
#else
			pixels[idx] = color.r;
			pixels[idx + 2] = color.b;
#endif
			pixels[idx + 1] = color.g;

		}
	}
}

void LDL_RenderSoftware::SetColor(const LDL_Color& color)
{
	_BaseRender.SetColor(color);
}

void LDL_RenderSoftware::Clear()
{
	size_t size = _Screen.Size().x * _Screen.Size().y * _Screen.Bpp();
	uint8_t* pixels = _Screen.Pixels();
	LDL_Color color = _BaseRender.Color();

	for (size_t i = 0; i < size; i += 3)
	{
#if defined(_WIN32)
		pixels[i] = color.b;
		pixels[i + 2] = color.r;
#else
		pixels[i] = color.r;
		pixels[i + 2] = color.b;
#endif
		pixels[i + 1] = color.g;
	}
}

void LDL_RenderSoftware::Draw(LDL_TextureSoftware* image, const LDL_Vec2i& pos)
{
	Draw(image, pos, image->Size(), LDL_Vec2i(0, 0), image->Size());
}

void LDL_RenderSoftware::Draw(LDL_TextureSoftware* image, const LDL_Vec2i& pos, const LDL_Vec2i& size)
{
	Draw(image, pos, size, LDL_Vec2i(0, 0), image->Size());
}

void LDL_RenderSoftware::Draw(LDL_TextureSoftware* image, const LDL_Vec2i& dstPos, const LDL_Vec2i& srcPos, const LDL_Vec2i& srcSize)
{
	Draw(image, dstPos, srcSize, srcPos, srcSize);
}

void LDL_RenderSoftware::Draw(LDL_TextureSoftware* image, const LDL_Vec2i& dstPos, const LDL_Vec2i& dstSize, const LDL_Vec2i& srcPos, const LDL_Vec2i& srcSize)
{
	assert(image != NULL);

	assert(dstPos.x >= 0);
	assert(dstPos.y >= 0);

	assert(dstSize.x >= 0);
	assert(dstSize.y >= 0);

	assert(srcPos.x >= 0);
	assert(srcPos.y >= 0);

	assert(srcSize.x >= 0);
	assert(srcSize.y >= 0);

	size_t x = dstPos.x;
	size_t y = dstPos.y;

	size_t   dstSizeX = _Screen.Size().x;
	size_t   dstSizeY = _Screen.Size().y;
	uint8_t  dstBpp   = _Screen.Bpp();
	uint8_t LDL_FAR* dstPixels = _Screen.Pixels();
	size_t   dstIndex = 0;

	size_t   srcSizeX = image->GetSurface()->Size().x;
	size_t   srcSizeY = image->GetSurface()->Size().y;
	uint8_t  srcBpp = image->GetSurface()->Bpp();
	uint8_t LDL_FAR* srcPixels = image->GetSurface()->Pixels();
	size_t   srcIndex = 0;

	size_t limitSizeX = 0;
	size_t limitSizeY = 0;

	if (srcSizeX + x > dstSizeX)
		limitSizeX = dstSizeX - x;
	else
		limitSizeX = srcSizeX;

	if (srcSizeY + y > dstSizeY)
		limitSizeY = dstSizeY - y;
	else
		limitSizeY = srcSizeY;

	for (size_t i = 0; i < limitSizeX; i++)
	{
		for (size_t j = 0; j < limitSizeY; j++)
		{
			dstIndex = (dstSizeX * (y + j) + (x + i)) * dstBpp;
			srcIndex = (srcSizeX * j + i) * srcBpp;

#if defined (_WIN32)
			dstPixels[dstIndex + 2] = srcPixels[srcIndex];
			dstPixels[dstIndex + 1] = srcPixels[srcIndex + 1];
			dstPixels[dstIndex] = srcPixels[srcIndex + 2];
#else
			dstPixels[dstIndex] = srcPixels[srcIndex];
			dstPixels[dstIndex + 1] = srcPixels[srcIndex + 1];
			dstPixels[dstIndex + 2] = srcPixels[srcIndex + 2];
#endif  
		}
	}
}
