/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <LDL/DOS/MainWin.hpp>
#include <assert.h>
#include <dos.h>

LDL_MainWindow::LDL_MainWindow(LDL_Result* result, const LDL_Vec2i& pos, const LDL_Vec2i& size, const char* title, int mode) :
	_Result(result),
	_BaseWindow(pos, size, title, mode)
{
	InitMouse();
}

LDL_MainWindow::~LDL_MainWindow()
{
	union REGS regs;

	regs.h.ah = 0x00;
	regs.h.al = 0x03;

	int86(0x10, &regs, &regs);
}

void LDL_MainWindow::Update()
{
}

uint8_t LDL_MainWindow::ConvertKey(size_t key)
{
	assert(key >= 0);

	return LDL_KeyboardKey::Unknown;
}

bool LDL_MainWindow::Running()
{
	return _Eventer.Running();
}

void LDL_MainWindow::PollEvents()
{
	LDL_Event event;

	if (MousePress(0x00))
	{
		event.Type = LDL_Event::IsMouseClick;
		event.Mouse.State = LDL_ButtonState::Pressed;
		event.Mouse.Button = LDL_MouseButton::Left;
		event.Mouse.PosX = 0;
		event.Mouse.PosY = 0;

		_Eventer.Push(event);
	}

	if (MousePress(0x01))
	{
		event.Type = LDL_Event::IsMouseClick;
		event.Mouse.State = LDL_ButtonState::Pressed;
		event.Mouse.Button = LDL_MouseButton::Right;
		event.Mouse.PosX = 0;
		event.Mouse.PosY = 0;

		_Eventer.Push(event);
	}

	if (MousePress(0x02))
	{
		event.Type = LDL_Event::IsMouseClick;
		event.Mouse.State = LDL_ButtonState::Pressed;
		event.Mouse.Button = LDL_MouseButton::Middle;
		event.Mouse.PosX = 0;
		event.Mouse.PosY = 0;

		_Eventer.Push(event);
	}
}

bool LDL_MainWindow::GetEvent(LDL_Event& event)
{
	if (!_Eventer.Empty())
	{
		_Eventer.Pop(event);

		return true;
	}

	return false;
}

bool LDL_MainWindow::WaitEvent(LDL_Event& event)
{
	return _Eventer.Running();
}

void LDL_MainWindow::StopEvent()
{
	_Eventer.Stop();
}

void LDL_MainWindow::Title(const char* title)
{
	_BaseWindow.Title(title);
}

const char* LDL_MainWindow::Title()
{
	return _BaseWindow.Title();
}

const LDL_Vec2i& LDL_MainWindow::Size()
{
	return _BaseWindow.Size();
}

const LDL_Vec2i& LDL_MainWindow::Pos()
{
	return _BaseWindow.Pos();
}

bool LDL_MainWindow::InitMouse()
{
	union REGS regs;

	regs.x.ax = 0;

	int86(0x33, &regs, &regs);

	bool result = regs.x.ax;

	if (!result)
	{
		return false;
	}

	return true;
}

bool LDL_MainWindow::MousePress(size_t button)
{
	union REGS regs;

	regs.x.ax = 0x05;
	regs.x.bx = button;

	int86(0x33, &regs, &regs);

	return regs.x.bx;
}