/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_BaseWin_hpp
#define LDL_BaseWin_hpp

#include <LDL/Vec2i.hpp>

class LDL_BaseWindow
{
public:
	enum
	{
		Max = 64
	};

	LDL_BaseWindow(const LDL_Vec2i& pos, const LDL_Vec2i& size, const char* title, int mode);
	~LDL_BaseWindow();
	const char* Title();
	void Title(const char* title);
	const LDL_Vec2i& Pos();
	void Pos(const LDL_Vec2i& pos);
	const LDL_Vec2i& Size();
	void Size(const LDL_Vec2i& size);
	int Mode();
private:
	LDL_Vec2i _Pos;
	LDL_Vec2i _Size;
	char      _Title[Max];
	int       _WindowMode;
};

#endif