/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_BmpLoad_hpp
#define LDL_BmpLoad_hpp

#include <LDL/Result.hpp>
#include <LDL/Vec2i.hpp>
#include <stdio.h>

struct LDL_BmpFileHeader
{
	uint16_t bfType;
	uint32_t bfSize;
	uint16_t bfReserved1;
	uint16_t bfReserved2;
	uint32_t bfOffBits;
};

struct LDL_BmpInfoHeader
{
	uint32_t biSize;
	int32_t  biWidth;
	int32_t  biHeight;
	uint16_t biPlanes;
	uint16_t biBitCount;
	uint32_t biCompression;
	uint32_t biSizeImage;
	int32_t  biXPelsPerMeter;
	int32_t  biYPelsPerMeter;
	uint32_t biClrUsed;
	uint32_t biClrImportant;
};

struct LDL_BmpPalette
{
	uint8_t blue;
	uint8_t green;
	uint8_t red;
	uint8_t alpha;
};

class LDL_BmpLoader
{
public:
	LDL_BmpLoader(LDL_Result* result);
	~LDL_BmpLoader();
	bool Load(const char* path);
	const LDL_Vec2i& Size();
	uint8_t Bpp();
	uint8_t* Pixels();
private:
	void BgrToRgb();
	bool CheckOpen(const char* path);
	bool CheckFileHeader();
	bool CheckInfoHeader();
	bool ReadBytes();

	LDL_Result* _Result;
	uint8_t* _Pixels;
	FILE* _Input;
	LDL_BmpFileHeader _FileHeader;
	LDL_BmpInfoHeader _InfoHeader;
	LDL_Vec2i _Size;
	uint8_t _Bpp;
};

#endif