/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_Renders_GL1Rndr_hpp
#define LDL_Renders_GL1Rndr_hpp

#include <LDL/Window.hpp>
#include <LDL/BaseRndr.hpp>
#include <LDL/OpenGL.hpp>
#include <LDL/Mat4f.hpp>
#include <LDL/Surface.hpp>

class LDL_Texture
{
public:
	LDL_Texture(const LDL_Vec2i& size, uint8_t* pixels, uint8_t bytesPerPixel);
	LDL_Texture(const LDL_Vec2i& size, uint8_t bytesPerPixel);
	~LDL_Texture();
	void Copy(const LDL_Vec2i& dstPos, const LDL_Vec2i& srcSize, uint8_t* pixels, uint8_t bytesPerPixel);
	void Copy(const LDL_Vec2i& dstPos, LDL_Surface* surface, const LDL_Vec2i& srcSize);
	const LDL_Vec2i& Size();
	const LDL_Vec2i& Quad();
	GLuint Id();
private:
	GLuint    _Id;
	LDL_Vec2i _Size;
	LDL_Vec2i _Quad;
};

class LDL_Render
{
public:
	LDL_Render(LDL_Window* window, LDL_Palette* palette = NULL);
	void Begin();
	void End();
	void Line(const LDL_Vec2i& pos1, const LDL_Vec2i& pos2);
	void Fill(const LDL_Vec2i& pos, const LDL_Vec2i& size);
	void SetColor(const LDL_Color& color);
	void Clear();
private:
	LDL_Window* _Window;
	LDL_BaseRender   _BaseRender;
	LDL_OpenGLLoader _OpenGLLoader;
	LDL_Mat4f        _Projection;
	LDL_Mat4f        _ModelView;
};

#endif