
if(LDL_BUILD_EXAMPLES AND LDL_BUILD_EXAMPLES_CPP11 AND NOT EMSCRIPTEN)
    enable_language(CXX)
    add_subdirectory("C++11")
endif()

if(LDL_BUILD_EXAMPLES AND LDL_BUILD_EXAMPLES_CPP98 AND NOT EMSCRIPTEN)
    enable_language(CXX)
    add_subdirectory("C++98")
endif()

if(LDL_BUILD_EXAMPLES AND LDL_BUILD_EXAMPLES_C89 AND NOT EMSCRIPTEN)
    add_subdirectory("C89")
endif()

if(LDL_BUILD_EXAMPLES AND EMSCRIPTEN)
    add_subdirectory("Emscripten")
endif()

file(COPY "${CMAKE_CURRENT_SOURCE_DIR}/Files" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
file(COPY "${CMAKE_CURRENT_SOURCE_DIR}/Files" DESTINATION "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
