
if(LDL_BUILD_EXAMPLES AND LDL_BUILD_EXAMPLES_CPP11)
    enable_language(CXX)
    add_subdirectory("C++11")
endif()

if(LDL_BUILD_EXAMPLES AND LDL_BUILD_EXAMPLES_CPP98)
    enable_language(CXX)
    add_subdirectory("C++98")
endif()

if(LDL_BUILD_EXAMPLES AND LDL_BUILD_EXAMPLES_C89)
    add_subdirectory("C89")
endif()

file(COPY "${CMAKE_CURRENT_SOURCE_DIR}/Files" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
file(COPY "${CMAKE_CURRENT_SOURCE_DIR}/Files" DESTINATION "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
