add_executable(OpenGL3_ParticleSystem "OpenGL3_ParticleSystem.c")
target_link_libraries(OpenGL3_ParticleSystem LDL)

add_executable(OpenGL3_Triangle "OpenGL3_Triangle.c")
target_link_libraries(OpenGL3_Triangle LDL)

add_executable(OpenGL3_RotatingCube "OpenGL3_RotatingCube.c")
target_link_libraries(OpenGL3_RotatingCube LDL)

add_executable(OpenGL3_ColoredCubeMouse "OpenGL3_ColoredCubeMouse.c")
target_link_libraries(OpenGL3_ColoredCubeMouse LDL)

add_executable(OpenGL3_FloatingSpheres "OpenGL3_FloatingSpheres.c")
target_link_libraries(OpenGL3_FloatingSpheres LDL)

add_executable(OpenGL3_TexturedSphere "OpenGL3_TexturedSphere.c")
target_link_libraries(OpenGL3_TexturedSphere LDL)

add_executable(OpenGL3_TexturedCubeLighting "OpenGL3_TexturedCubeLighting.c")
target_link_libraries(OpenGL3_TexturedCubeLighting LDL)

add_executable(OpenGL3_PlanetWithMoon "OpenGL3_PlanetWithMoon.c")
target_link_libraries(OpenGL3_PlanetWithMoon LDL)

add_executable(OpenGL3_DancingTorus "OpenGL3_DancingTorus.c")
target_link_libraries(OpenGL3_DancingTorus LDL)

add_executable(OpenGL3_AnimatedWaterSurface "OpenGL3_AnimatedWaterSurface.c")
target_link_libraries(OpenGL3_AnimatedWaterSurface LDL)
