
add_executable(OpenGL1_Rect "OpenGL1_Rect.c")
target_link_libraries(OpenGL1_Rect LDL)

add_executable(OpenGL1_Rotate "OpenGL1_Rotate.c")
target_link_libraries(OpenGL1_Rotate LDL)

add_executable(OpenGL1_Move "OpenGL1_Move.c")
target_link_libraries(OpenGL1_Move LDL)

add_executable(OpenGL1_FallingParticles "OpenGL1_FallingParticles.c")
target_link_libraries(OpenGL1_FallingParticles LDL)

add_executable(OpenGL1_Rotating3DCube "OpenGL1_Rotating3DCube.c")
target_link_libraries(OpenGL1_Rotating3DCube LDL)

add_executable(OpenGL1_RotatingColorfulTorus "OpenGL1_RotatingColorfulTorus.c")
target_link_libraries(OpenGL1_RotatingColorfulTorus LDL)

add_executable(OpenGL1_SnowfallParticles "OpenGL1_SnowfallParticles.c")
target_link_libraries(OpenGL1_SnowfallParticles LDL)

add_executable(OpenGL1_Interactive3DCube "OpenGL1_Interactive3DCube.c")
target_link_libraries(OpenGL1_Interactive3DCube LDL)

add_executable(OpenGL1_Animated3DTerrain "OpenGL1_Animated3DTerrain.c")
target_link_libraries(OpenGL1_Animated3DTerrain LDL)

add_executable(OpenGL1_FirstPersonMaze "OpenGL1_FirstPersonMaze.c")
target_link_libraries(OpenGL1_FirstPersonMaze LDL)

add_executable(OpenGL1_SolarSystem "OpenGL1_SolarSystem.c")
target_link_libraries(OpenGL1_SolarSystem LDL)

add_executable(OpenGL1_WaterWaveSimulation "OpenGL1_WaterWaveSimulation.c")
target_link_libraries(OpenGL1_WaterWaveSimulation LDL)

add_executable(OpenGL1_TargetShooter "OpenGL1_TargetShooter.c")
target_link_libraries(OpenGL1_TargetShooter LDL)

add_executable(OpenGL1_3DAtomModel "OpenGL1_3DAtomModel.c")
target_link_libraries(OpenGL1_3DAtomModel LDL)

add_executable(OpenGL1_FractalTree "OpenGL1_FractalTree.c")
target_link_libraries(OpenGL1_FractalTree LDL)

add_executable(OpenGL1_3DAnalogClock "OpenGL1_3DAnalogClock.c")
target_link_libraries(OpenGL1_3DAnalogClock LDL)

add_executable(OpenGL1_FireworksShow "OpenGL1_FireworksShow.c")
target_link_libraries(OpenGL1_FireworksShow LDL)

add_executable(OpenGL1_TerrainFlight "OpenGL1_TerrainFlight.c")
target_link_libraries(OpenGL1_TerrainFlight LDL)

add_executable(OpenGL1_SolarSystemInteractive "OpenGL1_SolarSystemInteractive.c")
target_link_libraries(OpenGL1_SolarSystemInteractive LDL)
