/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <LDL/ByteRead.hpp>
#include <string.h>

LDL_ByteReader::LDL_ByteReader() :
	_Endian(LDL_ByteReader::BigEndian),
	_File(NULL)
{
}

LDL_ByteReader::~LDL_ByteReader()
{
	Close();
}

bool LDL_ByteReader::Open(const char* path, uint8_t endian)
{
	_Endian = endian;

	Close();

	_File = fopen(path, "rb");

	return IsOpen();
}

void LDL_ByteReader::Close()
{
	if (IsOpen())
	{
		fclose(_File);
	}
}

bool LDL_ByteReader::IsOpen()
{
	return _File != NULL;
}

uint8_t LDL_ByteReader::u8()
{
	uint8_t result;
	uint8_t bytes[1];

	fread((char*)bytes, sizeof(bytes), 1, _File);

	result = bytes[0];

	return result;
}

int8_t LDL_ByteReader::i8()
{
	return u8();
}

uint16_t LDL_ByteReader::u16()
{
	uint16_t result;
	uint8_t bytes[2];

	fread((char*)bytes, sizeof(bytes), 1, _File);

	if (_Endian == LDL_ByteReader::BigEndian)
	{
		memcpy(&result, bytes, sizeof(bytes));
	}
	else
	{
		result = bytes[1] | (bytes[0] << 8);
	}

	return result;
}

int16_t LDL_ByteReader::i16()
{
	return u16();
}

uint32_t LDL_ByteReader::u32()
{
	uint32_t result;
	uint8_t bytes[4];

	fread((char*)bytes, sizeof(bytes), 1, _File);

	if (_Endian == LDL_ByteReader::BigEndian)
	{
		memcpy(&result, bytes, sizeof(bytes));
	}
	else
	{
		result = bytes[3] | (bytes[2] << 8) | (bytes[1] << 16) | (bytes[0] << 24);
	}

	return result;
}

int32_t LDL_ByteReader::i32()
{
	return u32();
}
