/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <LDL/Surface.hpp>
#include <assert.h>

LDL_Surface::LDL_Surface(const LDL_Vec2i& capacity, uint8_t bpp) :
	_Bpp(bpp),
	_Capacity(capacity),
	_Size(capacity)
{
	assert(capacity.x > 0);
	assert(capacity.y > 0);
	assert(bpp >= 1 && bpp <= 4);

	_Pixels = new uint8_t[_Capacity.x * _Capacity.y * bpp];
}

LDL_Surface::LDL_Surface(const LDL_Vec2i& capacity, const LDL_Vec2i& size, uint8_t bpp) :
	_Bpp(bpp),
	_Capacity(capacity),
	_Size(size)
{
	assert(capacity.x > 0);
	assert(capacity.y > 0);
	assert(size.x > 0);
	assert(size.y > 0);
	assert(size.x <= capacity.x);
	assert(size.y <= capacity.y);
	assert(bpp >= 1 && bpp <= 4);

	_Pixels = new uint8_t[_Capacity.x * _Capacity.y * bpp];
}

LDL_Surface::~LDL_Surface()
{
	delete _Pixels;
}

uint8_t* LDL_FAR LDL_Surface::Pixels()
{
	return _Pixels;
}

uint8_t LDL_Surface::Bpp()
{
	return _Bpp;
}

const LDL_Vec2i& LDL_Surface::Capacity()
{
	return _Capacity;
}

const LDL_Vec2i& LDL_Surface::Size()
{
	return _Size;
}