/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_RdrX_hpp
#define LDL_RdrX_hpp

#include "LDL_WinX.hpp"
/********************************************************************************************************************************
													  
********************************************************************************************************************************/
#if defined(LDL_RENDER_OPENGL1) || defined(LDL_RENDER_OPENGL3)
#include "LDL_GL.hpp"

void LDL_Normalize(const LDL_Color& color, GLclampf& r, GLclampf& g, GLclampf& b)
{
	r = color.r / 255.0f;
	g = color.g / 255.0f;
	b = color.b / 255.0f;
}
#endif
/********************************************************************************************************************************
												 	  LDL_BaseRender
********************************************************************************************************************************/
class LDL_BaseRender
{
public:
	LDL_BaseRender(const LDL_Vec2i& size) :
		_Size(size)
	{
	}

	const LDL_Vec2i& Size()
	{
		return _Size;
	}

	const LDL_Color& Color()
	{
		return _Current;
	}

	void SetColor(const LDL_Color& color)
	{
		_Current = color;
	}

private:
	LDL_Vec2i _Size;
	LDL_Color _Current;
};
/********************************************************************************************************************************
														LDL_Texture
********************************************************************************************************************************/
#if defined(LDL_RENDER_OPENGL1)

#elif defined(LDL_RENDER_OPENGL3)

#elif defined(LDL_RENDER_SOFTWARE)

#endif
/********************************************************************************************************************************
													     LDL_Render
********************************************************************************************************************************/
#if defined(LDL_RENDER_OPENGL1)
class LDL_Render
{
public:
	LDL_Render(LDL_Window* window):
		_Window(window),
		_BaseRender(_Window->Size()),
		_OpenGLLoader(1, 2)
	{
	}

	void Begin()
	{
	}

	void End()
	{
		_Window->Present();
	}

	void SetColor(const LDL_Color& color)
	{
		_BaseRender.SetColor(color);
	}

	void Clear()
	{
		GLclampf r;
		GLclampf g;
		GLclampf b;

		LDL_Normalize(_BaseRender.Color(), r, g, b);

		glClearColor(r, g, b, 1.0f);
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
	}
private:
	LDL_Window*    _Window;
	LDL_BaseRender _BaseRender;
	LDL_OpenGLLoader _OpenGLLoader;
};
#elif defined(LDL_RENDER_OPENGL3)

#elif defined(LDL_RENDER_SOFTWARE)

#endif

#endif
