/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_RdrX_hpp
#define LDL_RdrX_hpp
/********************************************************************************************************************************
													 Includes
********************************************************************************************************************************/
#include "LDL/LDL_WinX.hpp"
/********************************************************************************************************************************

********************************************************************************************************************************/
const int LDL_TextureCount = 12;
const int LDL_TextureSizes[LDL_TextureCount] = { 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536 };

int LDL_SelectTextureSize(const LDL_Vec2i& size)
{
	int w = size.x;
	int h = size.y;

	for (int i = 0; i < LDL_TextureCount; i++)
	{
		if (w <= LDL_TextureSizes[i] && h <= LDL_TextureSizes[i])
		{
			return LDL_TextureSizes[i];
		}
	}

	return 0;
}
/********************************************************************************************************************************

********************************************************************************************************************************/
#if defined(LDL_RENDER_OPENGL1) || defined(LDL_RENDER_OPENGL3)
#include "LDL_GL.hpp"

void LDL_GL_Check(const char* file, int line, const char* expression)
{
	GLenum code = glGetError();

	if (code != GL_NO_ERROR)
	{
		char error[32];
		memset(error, 0, sizeof(error));

		switch (code)
		{
		case GL_INVALID_ENUM:
			strcpy(error, "GL_INVALID_ENUM");
			break;
		case GL_INVALID_VALUE:
			strcpy(error, "GL_INVALID_VALUE");
			break;
		case GL_INVALID_OPERATION:
			strcpy(error, "GL_INVALID_OPERATION");
			break;
		case GL_STACK_OVERFLOW:
			strcpy(error, "GL_STACK_OVERFLOW");
			break;
		case GL_STACK_UNDERFLOW:
			strcpy(error, "GL_STACK_UNDERFLOW");
			break;
		case GL_OUT_OF_MEMORY:
			strcpy(error, "GL_OUT_OF_MEMORY");
			break;
		default:
			strcpy(error, "Unknown error");
		}

		printf("OpenGL Error: %s File: %s Line: %d Detail: %s", error, file, line, expression);
		LDL_Abort();
	}
}

#define LDL_GL_CHECK(expr)                       \
    do                                           \
    {                                            \
        expr;                                    \
        LDL_GL_Check(__FILE__, __LINE__, #expr); \
    } while (false)    


void LDL_Normalize(const LDL_Color& color, GLclampf& r, GLclampf& g, GLclampf& b)
{
	r = color.r / 255.0f;
	g = color.g / 255.0f;
	b = color.b / 255.0f;
}

GLuint LDL_CreateTexture(GLsizei width, GLsizei heigth, GLint format)
{
	GLuint result = 0;

	LDL_GL_CHECK(glGenTextures(1, (GLuint*)&result));

	LDL_GL_CHECK(glEnable(GL_TEXTURE_2D));

	LDL_GL_CHECK(glBindTexture(GL_TEXTURE_2D, (GLuint)result));

	LDL_GL_CHECK(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST));
	LDL_GL_CHECK(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST));

	LDL_GL_CHECK(glTexImage2D(GL_TEXTURE_2D, 0, format, width, heigth, 0, format, GL_UNSIGNED_BYTE, NULL));

	LDL_GL_CHECK(glDisable(GL_TEXTURE_2D));

	return result;
}

void LDL_DeleteTexture(GLint id)
{
	LDL_GL_CHECK(glDeleteTextures(0, (GLuint*)&id));
}

void LDL_DrawQuad(const LDL_Vec2i& dstPos, const LDL_Vec2i& dstSize, const LDL_Vec2i& srcPos, const LDL_Vec2i& srcSize, size_t textureSize)
{
	GLfloat x = (GLfloat)dstPos.x;
	GLfloat y = (GLfloat)dstPos.y;
	GLfloat w = (GLfloat)dstSize.x;
	GLfloat h = (GLfloat)dstSize.y;

	GLfloat cx = (GLfloat)srcPos.x;
	GLfloat cy = (GLfloat)srcPos.y;
	GLfloat cw = (GLfloat)srcSize.x;
	GLfloat ch = (GLfloat)srcSize.y;

	GLfloat dcx = cx / textureSize;
	GLfloat dcy = cy / textureSize;

	GLfloat dcw = (cx + cw) / textureSize;
	GLfloat dch = (cy + ch) / textureSize;

	glBegin(GL_QUADS);
	glTexCoord2f(dcx, dcy); glVertex2f(x, y);
	glTexCoord2f(dcw, dcy); glVertex2f(x + cw + (w - cw), y);
	glTexCoord2f(dcw, dch); glVertex2f(x + cw + (w - cw), y + ch + (h - ch));
	glTexCoord2f(dcx, dch); glVertex2f(x, y + ch + (h - ch));
	glEnd();
}
#endif
/********************************************************************************************************************************
													  LDL_BaseRender
********************************************************************************************************************************/
class LDL_BaseRender
{
public:
	LDL_BaseRender(const LDL_Vec2i& size) :
		_Size(size)
	{
	}

	const LDL_Vec2i& Size()
	{
		return _Size;
	}

	const LDL_Color& Color()
	{
		return _Current;
	}

	void SetColor(const LDL_Color& color)
	{
		_Current = color;
	}

private:
	LDL_Vec2i _Size;
	LDL_Color _Current;
};
/********************************************************************************************************************************
														LDL_Texture
********************************************************************************************************************************/
#if defined(LDL_RENDER_OPENGL1)
class LDL_Texture
{
public:
	LDL_Texture(const LDL_Vec2i& size, unsigned char* pixels, unsigned char bytesPerPixel) :
		_Id(0)
	{
		assert(size.x > 0);
		assert(size.y > 0);
		assert(bytesPerPixel >= 1 && bytesPerPixel <= 4);
		assert(pixels != NULL);

		_Size = size;

		GLint format = 0;

		if (bytesPerPixel == 3)
			format = GL_RGB;
		else
			format = GL_RGBA;

		int sz = LDL_SelectTextureSize(_Size);

		_Quad = LDL_Vec2i(sz, sz);

		_Id = LDL_CreateTexture((GLsizei)_Quad.x, (GLsizei)_Quad.y, format);

		Copy(LDL_Vec2i(0, 0), _Size, pixels, bytesPerPixel);
	}

	LDL_Texture(const LDL_Vec2i& size, unsigned char bytesPerPixel) :
		_Id(0)
	{
		_Size = size;

		GLint format = 0;

		if (bytesPerPixel == 3)
			format = GL_RGB;
		else
			format = GL_RGBA;

		int sz = LDL_SelectTextureSize(_Size);

		_Quad = LDL_Vec2i(sz, sz);

		_Id = LDL_CreateTexture((GLsizei)_Quad.x, (GLsizei)_Quad.y, format);
	}

	~LDL_Texture()
	{
		LDL_DeleteTexture((GLint)_Id);
	}

	void Copy(const LDL_Vec2i& dstPos, const LDL_Vec2i& srcSize, unsigned char* pixels, unsigned char bytesPerPixel)
	{
		GLint format = 0;

		if (bytesPerPixel == 3)
			format = GL_RGB;
		else
			format = GL_RGBA;

		LDL_GL_CHECK(glTexSubImage2D(GL_TEXTURE_2D, 0, (GLint)dstPos.x, (GLint)dstPos.y, (GLsizei)srcSize.x, (GLsizei)srcSize.y, format, GL_UNSIGNED_BYTE, pixels));
	}

	void Copy(const LDL_Vec2i& dstPos, LDL_Surface* surface, const LDL_Vec2i& srcSize)
	{
		Copy(dstPos, srcSize, surface->Pixels(), surface->BytesPerPixel());
	}

	const LDL_Vec2i& Size()
	{
		return _Size;
	}

	const LDL_Vec2i& Quad()
	{
		return _Quad;
	}

	GLuint Id()
	{
		return _Id;
	}
private:
	GLuint    _Id;
	LDL_Vec2i _Size;
	LDL_Vec2i _Quad;
};
#elif defined(LDL_RENDER_OPENGL3)

#elif defined(LDL_RENDER_SOFTWARE)

#endif
/********************************************************************************************************************************
														 LDL_Render
********************************************************************************************************************************/
#if defined(LDL_RENDER_OPENGL1)
class LDL_Render
{
public:
	LDL_Render(LDL_Window* window) :
		_Window(window),
		_BaseRender(_Window->Size()),
		_OpenGLLoader(1, 2)
	{
	}

	void Begin()
	{
		LDL_Vec2i size = _Window->Size();

		LDL_GL_CHECK(glViewport(0, 0, (GLsizei)size.x, (GLsizei)size.y));

		_Projection = Ortho(0.0f, (float)size.x, (float)size.y, 0.0f, -1.0f, 1.0f);
		LDL_GL_CHECK(glMatrixMode(GL_PROJECTION));
		LDL_GL_CHECK(glLoadMatrixf(_Projection.Values()));

		LDL_GL_CHECK(glMatrixMode(GL_MODELVIEW));
		LDL_GL_CHECK(glLoadMatrixf(_ModelView.Values()));
	}

	void End()
	{
		_Window->Present();
	}

	void Line(const LDL_Vec2i& pos1, const LDL_Vec2i& pos2)
	{
		GLclampf r;
		GLclampf g;
		GLclampf b;

		LDL_Normalize(_BaseRender.Color(), r, g, b);

		glBegin(GL_LINES);
		glColor3f(r, g, b);
		glVertex2i(pos1.x, pos1.y);
		glVertex2i(pos2.x, pos2.y);
		glEnd();
	}

	void Fill(const LDL_Vec2i& pos, const LDL_Vec2i& size)
	{
		GLclampf r;
		GLclampf g;
		GLclampf b;

		LDL_Normalize(_BaseRender.Color(), r, g, b);
		glColor3f(r, g, b);

		GLint x = (GLint)pos.x;
		GLint y = (GLint)pos.y;
		GLint w = (GLint)size.x;
		GLint h = (GLint)size.y;

		glBegin(GL_QUADS);
		glVertex2i(x, y + h);
		glVertex2i(x, y);
		glVertex2i(x + w, y);
		glVertex2i(x + w, y + h);
		glEnd();
	}

	void SetColor(const LDL_Color& color)
	{
		_BaseRender.SetColor(color);
	}

	void Clear()
	{
		GLclampf r;
		GLclampf g;
		GLclampf b;

		LDL_Normalize(_BaseRender.Color(), r, g, b);

		glClearColor(r, g, b, 1.0f);
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
	}

	void Draw(LDL_Texture* image, const LDL_Vec2i& pos)
	{
		Draw(image, pos, image->Size(), LDL_Vec2i(0, 0), image->Size());
	}

	void Draw(LDL_Texture* image, const LDL_Vec2i& pos, const LDL_Vec2i& size)
	{
		Draw(image, pos, size, LDL_Vec2i(0, 0), image->Size());
	}

	void Draw(LDL_Texture* image, const LDL_Vec2i& dstPos, const LDL_Vec2i& srcPos, const LDL_Vec2i& srcSize)
	{
		Draw(image, dstPos, srcSize, srcPos, srcSize);
	}

	void Draw(LDL_Texture* image, const LDL_Vec2i& dstPos, const LDL_Vec2i& dstSize, const LDL_Vec2i& srcPos, const LDL_Vec2i& srcSize)
	{
		assert(image);

		LDL_GL_CHECK(glEnable(GL_TEXTURE_2D));
		LDL_GL_CHECK(glBindTexture(GL_TEXTURE_2D, image->Id()));

		LDL_DrawQuad(dstPos, dstSize, srcPos, srcSize, image->Quad().x);

		LDL_GL_CHECK(glDisable(GL_TEXTURE_2D));
	}

private:
	LDL_Window* _Window;
	LDL_BaseRender   _BaseRender;
	LDL_OpenGLLoader _OpenGLLoader;
	LDL_Mat4f        _Projection;
	LDL_Mat4f        _ModelView;
};
#elif defined(LDL_RENDER_OPENGL3)

#elif defined(LDL_RENDER_SOFTWARE)
class LDL_Render
{
public:
	LDL_Render(LDL_Window* window) :
		_Window(window),
		_BaseRender(_Window->Size()),
		_Screen(_Window->Size(), _Window->Size(), 3)
	{
	}

	void Begin()
	{
	}

	void End()
	{
		_Window->Present(_Screen.Pixels(), _Screen.BytesPerPixel());
		_Window->Present();
	}

	void Line(const LDL_Vec2i& pos1, const LDL_Vec2i& pos2)
	{
	}

	void Fill(const LDL_Vec2i& pos, const LDL_Vec2i& size)
	{
		assert(size.x > 0);
		assert(size.y > 0);

		int x = pos.x;
		int y = pos.y;

		unsigned char* pixels = _Screen.Pixels();
		LDL_Color color = _BaseRender.Color();

		for (int i = 0; i < size.x; i++)
		{
			for (int j = 0; j < size.y; j++)
			{
				int idx = (_Screen.Size().x * (y + j) + (x + i)) * _Screen.BytesPerPixel();

#if defined(_WIN32)
				pixels[idx] = color.b;
				pixels[idx + 2] = color.r;
#else
				pixels[idx] = color.r;
				pixels[idx + 2] = color.b;
#endif
				pixels[idx + 1] = color.g;

			}
		}
	}

	void SetColor(const LDL_Color& color)
	{
		_BaseRender.SetColor(color);
	}

	void Clear()
	{
		size_t size = _Screen.Size().x * _Screen.Size().y * _Screen.BytesPerPixel();
		unsigned char* pixels = _Screen.Pixels();
		LDL_Color color = _BaseRender.Color();

		for (size_t i = 0; i < size; i += 3)
		{
#if defined(_WIN32)
			pixels[i] = color.b;
			pixels[i + 2] = color.r;
#else
			pixels[i] = color.r;
			pixels[i + 2] = color.b;
#endif
			pixels[i + 1] = color.g;
		}
	}
private:
	LDL_Window* _Window;
	LDL_BaseRender _BaseRender;
	LDL_Surface    _Screen;
};
#endif

#endif
