/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_Surface_hpp
#define LDL_Surface_hpp

#include <LDL/Vec2i.hpp>
#include <LDL/Palette.hpp>
#include <LDL/Alpha.hpp>

class LDL_Surface
{
public:
	LDL_Surface(const LDL_Vec2i& capacity, uint8_t bpp);
	LDL_Surface(const LDL_Vec2i& capacity, const LDL_Vec2i& size, uint8_t bpp);
	LDL_Surface(const LDL_Vec2i& capacity, LDL_Palette* palette);
	LDL_Surface(const LDL_Vec2i& capacity, const LDL_Vec2i& size, LDL_Palette* palette);
	LDL_Surface(const LDL_Vec2i& capacity, const LDL_Vec2i& size, uint8_t * pixels, LDL_Palette* palette);
	~LDL_Surface();
	uint8_t* LDL_FAR Pixels();
	uint8_t Bpp();
	const LDL_Vec2i& Capacity();
	const LDL_Vec2i& Size();
	LDL_Palette* Palette();
	void Palette(LDL_Palette* palette);
	void Resize(const LDL_Vec2i& size);
	const LDL_Alpha& Alpha();
	void SetAlpha(LDL_Alpha& alpha);
private:
	uint8_t          _Bpp;
	uint8_t* LDL_FAR _Pixels;
	LDL_Vec2i        _Capacity;
	LDL_Vec2i        _Size;
	LDL_Palette      _Palette;
	LDL_Alpha        _Alpha;
};

#endif